MockDataProject/Models/MockData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace MockDataProject.Models
{
    public class MockData
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }

        [StringLength(50)]
        public string LastName { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }
}

MockDataProject/Models/MockDataContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace MockDataProject.Models
{
    public class MockDataContext : DbContext
    {
        public DbSet<MockData> MockDatas { get; set; }
    }
}

MockDataProject/Models/MockDataProjectContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MockDataProject.Models
{
    public class MockDataProjectContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public MockDataProjectContext() : base("name=MockDataProjectContext")
        {
        }

        public System.Data.Entity.DbSet<MockDataProject.Models.MockData> MockDatas { get; set; }
    }
}

MockDataProject/Controllers/MockDataController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using MockDataProject.Models;

namespace MockDataProject.Controllers
{
    public class MockDataController : Controller
    {
        private MockDataContext db = new MockDataContext();

        // GET: MockData
        public ActionResult Index()
        {
            return View(db.MockDatas.ToList());
        }

        // GET: MockData/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MockData/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Email")] MockData mockData)
        {
            if (ModelState.IsValid)
            {
                db.MockDatas.Add(mockData);
                db.SaveChanges();

                // Return the JSON data for the new entry
                return Json(new { success = true, data = mockData });
            }

            return Json(new { success = false });
        }

        // GET: MockData/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MockData mockData = db.MockDatas.Find(id);
            if (mockData == null)
            {
                return HttpNotFound();
            }
            return View(mockData);
        }

        // POST: MockData/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Email")] MockData mockData)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mockData).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mockData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var mockData = db.MockDatas.Find(id);
            if (mockData == null)
            {
                return Json(new { success = false });
            }

            db.MockDatas.Remove(mockData);
            db.SaveChanges();

            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MockDataProject/Views/MockData/Delete.cshtml
@model MockDataProject.Models.MockData

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MockData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MockDataProject/Views/MockData/Details.cshtml
@model MockDataProject.Models.MockData

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MockData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MockDataProject/Views/MockData/Edit.cshtml
@model MockDataProject.Models.MockData

@{
    ViewBag.Title = "Edit MockData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit MockData</h2>

@using (Html.BeginForm("Edit", "MockData", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MockDataProject/Views/MockData/Index.cshtml
@model IEnumerable<MockDataProject.Models.MockData>

@{
    ViewBag.Title = "MockData List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center">@ViewBag.Title</h2>
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h4>MockData Entries</h4>
                </div>
                <div class="card-body">
                    <!-- Form to create new MockData -->
                    <form id="createMockDataForm" class="mb-4">
                        @Html.AntiForgeryToken() <!-- Include Anti-Forgery Token -->
                        <div class="form-group row">
                            <label for="FirstName" class="col-sm-2 col-form-label">First Name</label>
                            <div class="col-sm-4">
                                <input type="text" id="FirstName" name="FirstName" class="form-control" placeholder="First Name" required />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="LastName" class="col-sm-2 col-form-label">Last Name</label>
                            <div class="col-sm-4">
                                <input type="text" id="LastName" name="LastName" class="form-control" placeholder="Last Name" required />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="Email" class="col-sm-2 col-form-label">Email</label>
                            <div class="col-sm-4">
                                <input type="email" id="Email" name="Email" class="form-control" placeholder="Email" required />
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-2"></div> <!-- This empty column is for alignment purposes -->
                            <div class="col-sm-4">
                                <button type="submit" class="btn btn-success">
                                    <i class="fa fa-plus"></i> Create New
                                </button>
                            </div>
                        </div>
                    </form>

                    @if (Model.Any())
                    {
                        <table class="table table-striped table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>Email</th>
                                    <th class="text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody id="mockDataTable">
                                @foreach (var item in Model)
                                {
                                    <tr id="row-@item.Id">
                                        <td>@Html.DisplayFor(modelItem => item.FirstName)</td>
                                        <td>@Html.DisplayFor(modelItem => item.LastName)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Email)</td>
                                        <td class="text-right">
                                            <a href="@Url.Action("Edit", "MockData", new { id = item.Id })" class="btn btn-warning btn-sm edit-mockdata">
                                                <i class="fa fa-edit"></i> Edit
                                            </a>
                                            <button type="button" class="btn btn-danger btn-sm delete-mockdata" data-id="@item.Id">
                                                <i class="fa fa-trash"></i> Delete
                                            </button>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <div class="alert alert-info text-center" role="alert">
                            No MockData entries found. Use the form above to add a new entry.
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Ensure FontAwesome is included for icons -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
   $(document).ready(function() {
    // Handle form submission via AJAX
    $('#createMockDataForm').on('submit', function(event) {
        event.preventDefault();

        var form = $(this);
        var formData = form.serialize(); // Serialize form data

        $.ajax({
            url: '@Url.Action("Create", "MockData")',
            type: 'POST',
            data: formData,
            success: function(response) {
                if (response && response.success) {
                    // Construct the new row HTML
                    var newRow = `
                        <tr id="row-${response.data.Id}">
                            <td>${response.data.FirstName}</td>
                            <td>${response.data.LastName}</td>
                            <td>${response.data.Email}</td>
                            <td class="text-right">
                                <a href="@Url.Action("Edit", "MockData")/${response.data.Id}" class="btn btn-warning btn-sm edit-mockdata">
                                    <i class="fa fa-edit"></i> Edit
                                </a>
                                <button type="button" class="btn btn-danger btn-sm delete-mockdata" data-id="${response.data.Id}">
                                    <i class="fa fa-trash"></i> Delete
                                </button>
                            </td>
                        </tr>`;

                    $('#mockDataTable').append(newRow);
                    form[0].reset(); // Clear the form fields
                } else {
                    alert('Failed to create the entry.');
                }
            },
            error: function(xhr, status, error) {
                alert('An error occurred: ' + error);
            }
        });
    });


        $(document).on('click', '.delete-mockdata', function() {
        var id = $(this).data('id');
        var row = $('#row-' + id);

        if (confirm('Are you sure you want to delete this entry?')) {
            $.ajax({
                url: '@Url.Action("Delete", "MockData")/' + id,
                type: 'POST',
                data: {
                    __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val() // Include Anti-Forgery Token
                },
                success: function(response) {
                    if (response.success) {
                        row.remove(); // Remove the row from the table
                    } else {
                        alert('Failed to delete the entry.');
                    }
                },
                error: function(xhr, status, error) {
                    alert('An error occurred: ' + error);
                }
            });
        }
    });
    });
</script>

MockDataProject/Views/MockData/_MockDataTableRow.cshtml
@model MockDataProject.Models.MockData

<tr id="row-@Model.Id">
    <td>@Model.FirstName</td>
    <td>@Model.LastName</td>
    <td>@Model.Email</td>
    <td class="text-right">
        <a href="@Url.Action("Edit", "MockData", new { id = Model.Id })" class="btn btn-warning btn-sm">
            <i class="fa fa-edit"></i> Edit
        </a>
        @using (Html.BeginForm("Delete", "MockData", FormMethod.Post, new { @class = "d-inline" }))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden("id", Model.Id)
            <button type="submit" class="btn btn-danger btn-sm">
                <i class="fa fa-trash"></i> Delete
            </button>
        }
    </td>
</tr>

MockDataProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MockDataProject</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" >MockDataProject</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MockDataProject</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>